const ct = [
  { label: 'AFG (Afghanistan)', value: '252' },
  { label: 'AGO (Angola)', value: '151' },
  { label: 'AND (Andorra)', value: '082' },
  { label: 'ANG (Anguilla)', value: '620' },
  { label: 'ARG (Argentina)', value: '703' },
  { label: 'ARM (Armenia)', value: '049' },
  { label: 'ATG (Antigua And Barbuda)', value: '621' },
  { label: 'AUS (Australia)', value: '305' },
  { label: 'AUT (Austria)', value: '011' },
  { label: 'AZE (Azerbaijan)', value: '120' },
  { label: 'BDI (Burundi)', value: '154' },
  { label: 'BEL (Belgium)', value: '131' },
  { label: 'BEN (Benin)', value: '160' },
  { label: 'BFA (Burkina Faso)', value: '188' },
  { label: 'BGD (Bangladesh)', value: '212' },
  { label: 'BGR (Bulgaria)', value: '083' },
  { label: 'BHR (Bahrain)', value: '253' },
  { label: 'BHS (Bahamas)', value: '622' },
  { label: 'BIH (Bosnia and Herzegovina)', value: '048' },
  { label: 'ARE (United Arab Emirates)', value: '280' },
  { label: 'BLR (Belarus)', value: '051' },
  { label: 'BLZ (Belize)', value: '541' },
  { label: 'BMU (Bermuda)', value: '601' },
  { label: 'BOL (Bolivia)', value: '751' },
  { label: 'BRA (Brazil)', value: '709' },
  { label: 'BRB (Barbados)', value: '610' },
  { label: 'BRN (Brunei Darussalam)', value: '255' },
  { label: 'BTN (Bhutan)', value: '254' },
  { label: 'BWA (Botswana)', value: '153' },
  { label: 'CAF (Central African Republic)', value: '157' },
  { label: 'CAN (Canada)', value: '511' },
  { label: 'CHE (Switzerland)', value: '041' },
  { label: 'CHL (Chile)', value: '721' },
  { label: 'CHN (China (Hong Kong SAR))', value: '200' },
  { label: 'CHN (Macao)', value: '198' },
  { label: 'CHN (China)', value: '202' },
  { label: 'CIV (Ivory Coast)', value: '169' },
  { label: 'CMR (Cameroon)', value: '155' },
  { label: 'COD (Democratic Rep. of Congo)', value: '158' },
  { label: 'COG (Republic of Congo)', value: '159' },
  { label: 'COL (Colombia)', value: '722' },
  { label: 'COM (Comoros)', value: '905' },
  { label: 'DJI (Djibouti)', value: '183' },
  { label: 'ERI (Eritrea)', value: '162' },
  { label: 'GAB (Gabon)', value: '163' },
  { label: 'GBD (UK - Brit. overseas terr.)', value: '005' },
  { label: 'GBN (UK - Brit. Ntl. Overseas)', value: '010' },
  { label: 'GBO (UK - Brit. overseas citizen)', value: '004' },
  { label: 'GBP (UK - Brit. protected person)', value: '917' },
  { label: 'GBR (UK - British citizen)', value: '003' },
  { label: 'GBS (UK - British subject)', value: '001' },
  { label: 'GHA (Ghana)', value: '165' },
  { label: 'HND (Honduras)', value: '545' },
  { label: 'IND (India)', value: '205' },
  { label: 'JPN (Japan)', value: '207' },
  { label: 'KOR (Korea, South)', value: '258' },
  { label: 'TWN (Taiwan)', value: '203' },
];